<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#복습" data-toc-modified-id="복습-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>복습</a></span><ul class="toc-item"><li><span><a href="#polymorphism-(다형성)" data-toc-modified-id="polymorphism-(다형성)-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>polymorphism (다형성)</a></span></li><li><span><a href="#broadcasting" data-toc-modified-id="broadcasting-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>broadcasting</a></span></li><li><span><a href="#shape-&amp;-dtype" data-toc-modified-id="shape-&amp;-dtype-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>shape &amp; dtype</a></span></li></ul></li><li><span><a href="#array-모양-바꾸기" data-toc-modified-id="array-모양-바꾸기-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>array 모양 바꾸기</a></span><ul class="toc-item"><li><span><a href="#reshape" data-toc-modified-id="reshape-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>reshape</a></span></li><li><span><a href="#resize" data-toc-modified-id="resize-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>resize</a></span></li></ul></li><li><span><a href="#array-쪼개기" data-toc-modified-id="array-쪼개기-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>array 쪼개기</a></span><ul class="toc-item"><li><span><a href="#split" data-toc-modified-id="split-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>split</a></span></li><li><span><a href="#hsplit-&amp;-vsplit" data-toc-modified-id="hsplit-&amp;-vsplit-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>hsplit &amp; vsplit</a></span></li><li><span><a href="#indices_or_sections" data-toc-modified-id="indices_or_sections-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>indices_or_sections</a></span></li></ul></li><li><span><a href="#array-합치기" data-toc-modified-id="array-합치기-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>array 합치기</a></span><ul class="toc-item"><li><span><a href="#hstack-&amp;-vstack" data-toc-modified-id="hstack-&amp;-vstack-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>hstack &amp; vstack</a></span></li><li><span><a href="#dstack" data-toc-modified-id="dstack-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>dstack</a></span></li><li><span><a href="#stack" data-toc-modified-id="stack-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>stack</a></span></li><li><span><a href="#concatenate" data-toc-modified-id="concatenate-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>concatenate</a></span></li></ul></li><li><span><a href="#차원-확장" data-toc-modified-id="차원-확장-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>차원 확장</a></span><ul class="toc-item"><li><span><a href="#reshape" data-toc-modified-id="reshape-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>reshape</a></span></li><li><span><a href="#stack" data-toc-modified-id="stack-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>stack</a></span></li><li><span><a href="#newaxis" data-toc-modified-id="newaxis-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>newaxis</a></span></li><li><span><a href="#expand_dims" data-toc-modified-id="expand_dims-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>expand_dims</a></span></li></ul></li><li><span><a href="#indexer" data-toc-modified-id="indexer-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>indexer</a></span><ul class="toc-item"><li><span><a href="#r_" data-toc-modified-id="r_-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>r_</a></span></li><li><span><a href="#c_" data-toc-modified-id="c_-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>c_</a></span></li><li><span><a href="#s_" data-toc-modified-id="s_-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>s_</a></span></li></ul></li><li><span><a href="#ix_" data-toc-modified-id="ix_-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>ix_</a></span></li><li><span><a href="#array-한줄로-펴기" data-toc-modified-id="array-한줄로-펴기-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>array 한줄로 펴기</a></span><ul class="toc-item"><li><span><a href="#flatten" data-toc-modified-id="flatten-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>flatten</a></span></li><li><span><a href="#ravel" data-toc-modified-id="ravel-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>ravel</a></span></li></ul></li><li><span><a href="#전치(차원-교환)" data-toc-modified-id="전치(차원-교환)-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>전치(차원 교환)</a></span><ul class="toc-item"><li><span><a href="#T" data-toc-modified-id="T-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>T</a></span></li><li><span><a href="#transpose" data-toc-modified-id="transpose-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>transpose</a></span></li><li><span><a href="#swapaxes" data-toc-modified-id="swapaxes-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>swapaxes</a></span></li></ul></li><li><span><a href="#structured-array" data-toc-modified-id="structured-array-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>structured array</a></span><ul class="toc-item"><li><span><a href="#pandas는-structured-array와-비슷하다." data-toc-modified-id="pandas는-structured-array와-비슷하다.-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>pandas는 structured array와 비슷하다.</a></span></li></ul></li><li><span><a href="#파일" data-toc-modified-id="파일-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>파일</a></span><ul class="toc-item"><li><span><a href="#2가지-종류의-파일-형태" data-toc-modified-id="2가지-종류의-파일-형태-11.1"><span class="toc-item-num">11.1&nbsp;&nbsp;</span>2가지 종류의 파일 형태</a></span></li><li><span><a href="#파일의-요소는-3가지" data-toc-modified-id="파일의-요소는-3가지-11.2"><span class="toc-item-num">11.2&nbsp;&nbsp;</span>파일의 요소는 3가지</a></span></li><li><span><a href="#open" data-toc-modified-id="open-11.3"><span class="toc-item-num">11.3&nbsp;&nbsp;</span>open</a></span></li><li><span><a href="#with" data-toc-modified-id="with-11.4"><span class="toc-item-num">11.4&nbsp;&nbsp;</span>with</a></span></li><li><span><a href="#pickle" data-toc-modified-id="pickle-11.5"><span class="toc-item-num">11.5&nbsp;&nbsp;</span>pickle</a></span></li><li><span><a href="#numpy-파일-저장-&amp;-불러오기" data-toc-modified-id="numpy-파일-저장-&amp;-불러오기-11.6"><span class="toc-item-num">11.6&nbsp;&nbsp;</span>numpy 파일 저장 &amp; 불러오기</a></span></li><li><span><a href="#numpy-텍스트-파일-읽기" data-toc-modified-id="numpy-텍스트-파일-읽기-11.7"><span class="toc-item-num">11.7&nbsp;&nbsp;</span>numpy 텍스트 파일 읽기</a></span></li><li><span><a href="#loadtxt" data-toc-modified-id="loadtxt-11.8"><span class="toc-item-num">11.8&nbsp;&nbsp;</span>loadtxt</a></span></li><li><span><a href="#genfromtxt" data-toc-modified-id="genfromtxt-11.9"><span class="toc-item-num">11.9&nbsp;&nbsp;</span>genfromtxt</a></span></li></ul></li><li><span><a href="#데이터를-OPEN(Translation)시켜서-시작" data-toc-modified-id="데이터를-OPEN(Translation)시켜서-시작-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>데이터를 OPEN(Translation)시켜서 시작</a></span><ul class="toc-item"><li><span><a href="#pandas" data-toc-modified-id="pandas-12.1"><span class="toc-item-num">12.1&nbsp;&nbsp;</span>pandas</a></span></li></ul></li></ul></div>

# [AI 오픈 이노베이션] 기본 저녁반<a class="tocSkip">
GitHub link: [https://github.com/realblack0/8th_ai_lecture_fundamental](https://github.com/realblack0/8th_ai_lecture_fundamental)  
E-Mail: realblack0@gmail.com

## 복습

### polymorphism (다형성)

In [1]:
def plus(a, b):
    return a+b

In [2]:
plus(1, 3)

4

argument의 data type을 지정하지 않기 때문에, 문자열을 넣어도 된다. 

In [3]:
plus('1', '2')

'12'

annotation을 쓸 수 있지만, 강제성은 없다. 

In [4]:
def plus(a:int, b:int) -> int:
    return a+b

In [5]:
plus.__annotations__

{'a': int, 'b': int, 'return': int}

강제성은 없기 때문에 문자열 여전히 넣을 수 있다. 

In [6]:
plus('1', '2')

'12'

### broadcasting

numpy에서는 shape을 맞추지 않아도, 특수한 경우에는 알아서 shape을 맞춰서 연산해준다.
- 1차원일 때
- scalar일 때

In [7]:
import numpy as np

In [8]:
a = np.array([[1,2], [3,4]])

In [9]:
# array와 scalar 연산 -> broadcasting
a + 1

array([[2, 3],
       [4, 5]])

### shape & dtype

numpy에서는 shape과 dtype이 가장 중요하다.

In [10]:
a.shape

(2, 2)

In [11]:
a.dtype

dtype('int32')

다음은 모두 shape과 dtype으로 알 수 있다. 

In [17]:
a.itemsize, a.strides, a.size

(4, (32, 4), 24)

## array 모양 바꾸기

### reshape

reshape은 차원을 바꿔주는 것이다. 

In [14]:
a = np.arange(24).reshape(3,8)

In [15]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

`shift` + `tab` 해보면 shape이라는 인자만 받을 수 있다.  
signature대로라면 다음 코드는 Error가 나야하지만, 내부적으로 실행되도록 처리되어 있다. 

In [18]:
a.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

mutable이 아니므로, a는 그대로이다. 

In [19]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

재할당해서 사용해야 한다.

In [20]:
a = a.reshape(2,3,4)

In [21]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array의 원소 개수와 reshape 후 원소 개수가 맞아야 한다.  
a의 원소는 24개인데, (2,3,5)는 원소 30개이다.  
개수가 안 맞아서 에러가 발생한다.

In [ ]:
# Error
a.reshape(2,3,5)

음수를 쓰면, 알아서 shape을 맞춰준다.

In [23]:
a.reshape(2,3,-1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

음수이기만 하면 -100도 상관없다.

In [24]:
a.reshape(2,3,-100)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

음수를 2개 이상 쓸 수는 없다.  
음수는 다른 차원들이 정해진 상황에서 남은 하나의 차원만 알아서 맞춰준다. 

In [ ]:
# Error
a.reshape(-1,3,-1)

나중에 배울 tensorflow에서도 reshape은 자주 사용한다. 

In [26]:
import tensorflow as tf

In [27]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

In [28]:
X_train.shape

(60000, 28, 28)

reshape으로 차원을 늘릴 수도 있다. 

In [30]:
X_train = X_train.reshape(60000, 28, 28, 1)
X_train.shape

(60000, 28, 28, 1)

### resize

size는 원소 개수를 알려준다.

In [32]:
a = np.arange(24)

In [33]:
a.size

24

resize는 원소의 개수를 변형시킨다.

In [34]:
# mutable이다. return이 없고 자기 자신을 바꾼다. -> reshape과 차이점1
# 원래의 원소 개수와 변형 후의 원소 개수가 안 맞아도 된다. -> reshape과 차이점2
a.resize(2,3,1)

변형하기 전보다 작게 하니 원소 개수가 줄어들었다. 

In [35]:
a

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

변형하기 전보다 크게 바꾸면 0으로 채워진다.

In [37]:
a = np.arange(24)
a.resize(2,3,8)

In [39]:
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]]])

## array 쪼개기

In [15]:
a = np.arange(24)

### split

In [41]:
# a를 2개로 나눈다.
np.split(a, 2)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [43]:
# a는 바뀌지 않았다. 
# immutable
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [42]:
# a를 3개로 나눈다.
# 결과값이 array로 구성된 list이다. 
np.split(a, 3)

[array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21, 22, 23])]

### hsplit & vsplit

`split`은 axis 파라미터가 있다 .

In [16]:
np.split(a, 2, axis=0)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

`hsplit`, `vsplit`은 axis 파라미터가 없다.  
`hsplit`은 axis=0 고정, `vsplit`은 axis=1 고정이다.

In [45]:
np.hsplit(a, 2) # h: horizontal (수평)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

a는 수직으로 나눌 수 없어서 `vsplit`이 에러를 일으킨다. 

In [ ]:
# Error
np.vsplit(a, 2) # v: vertical (수직)

reshape 후 수직으로 나눌 수 있으므로 에러를 발생시키지 않는다.

In [17]:
a = np.arange(24)
b = a.reshape(4,6)

In [18]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
np.vsplit(b, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

### indices_or_sections

split 시리즈 함수들의 두번째 파라미터 이름은 indices_or_sections 이다.  
숫자를 묶어서 넣으면 구간으로 쪼개준다.

In [51]:
# section
# 처음 ~ 2까지  //  2 ~ 3  //  3부터 ~ 끝까지
np.hsplit(a, (2,3))

[array([0, 1]),
 array([2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23])]

In [52]:
# section
# 처음 ~ 3까지  //  3 ~ 3  //  3부터 ~ 끝까지
# 결과에서 3 ~ 3에 해당하는 array는 비어있는 것에 유의
np.hsplit(a, (3,3))

[array([0, 1, 2]),
 array([], dtype=int32),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23])]

## array 합치기

합치기 전에 먼저 나눠진 array를 만든다.

In [24]:
# unpacking
a = np.arange(24)
x, y, z = np.split(a, 3)

In [25]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
y

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
z

array([16, 17, 18, 19, 20, 21, 22, 23])

### hstack & vstack

`hstack`은 horiziontal(가로)로 합쳐준다.

In [ ]:
# Error
np.hstack(x, y)

In [57]:
# tuple로 묶어서 넣어줘야한다.
np.hstack((x, y))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

`vstack`은 vertical(세로)로 합쳐준다.

In [59]:
np.vstack((x, y))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

### dstack

`dstack`은 합쳐서 3차원으로 만들어준다.  
합칠 array들이 1차원, 2차원일 경우는 차원을 늘린 후 합친다. 
합쳐지는 차원은 axis=2이다.

In [63]:
np.dstack((x, y)) # 3차원

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11],
        [ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [33]:
# x는 shape이 (n,)인 1차원이므로 (1,n,1)인 3차원으로 변환된다.
# y도 shape이 (m,)인 1차원으므로 (1,m,1)인 3차원으로 변환된다.
# axis=2 방향으로 합쳐지므로 out의 shape은 (1,8,2)
np.dstack((x, y)).shape

(1, 8, 2)

### stack

array의 크기를 줄여서 보기 쉽게한다.

In [42]:
a = np.arange(12).reshape(3,4)

In [43]:
x, y = np.split(a, 2, axis=1)

In [45]:
x

array([[0, 1],
       [4, 5],
       [8, 9]])

In [46]:
y

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

`stack`은 합칠 차원을 지정해서 합친다.

In [44]:
print(np.stack((x,y)).shape)
np.stack((x,y)) # default value : axis=0

(2, 3, 2)


array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

In [47]:
print(np.stack((x,y), axis=1).shape)
np.stack((x,y), axis=1)

(3, 2, 2)


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

-2는 뒤에서 두번째 차원이라는 뜻이다.

In [49]:
print(np.stack((x,y), axis=-2).shape)
np.stack((x,y), axis=-2)

(3, 2, 2)


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

tuple 안에 array가 1개여도 된다.

In [87]:
np.stack((x,))

array([[[0, 1],
        [4, 5],
        [8, 9]]])

### concatenate

`concatenate`는 axis 방향에 그대로 합쳐준다.  
※ `stack`은 axis 방향에 새로운 차원을 만들어서 합쳐준다.

In [86]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 차원 확장

numpy는 차원을 확장하는 여러가지 방법이 있다.

### reshape

In [96]:
a = np.arange(12).reshape(3, 4)

In [99]:
# arange는 1차원
# reshape 후 a는 2차원
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### stack

In [97]:
# tuple에 원소가 1개 있으면 차원만 확장시켜준다.
np.stack((a,))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

### newaxis

인덱싱할 때 `np.newaxis`를 쓰면 차원을 늘릴 수 있다.

In [100]:
a[np.newaxis]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [111]:
# 위 코드는 :가 생략된 것이다. 
# 첫번째 자리에 새로운 차원을 만든다.
print(a[np.newaxis, :, :].shape)
a[np.newaxis, :, :]

(1, 3, 4)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

1번째 자리에 새로운 차원을 만드는 방법:  
`np.newaxis`를 1번째 자리에 넣는다. 

In [104]:
print(a[:, np.newaxis].shape)
a[:, np.newaxis, :]

(3, 1, 4)


array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

np.newaxis는 None이다.

In [103]:
# out이 없으면 None이다.
np.newaxis

In [107]:
np.newaxis is None

True

`np.newaxis` 대신에 `None`을 써도 된다.  
`None`은 직관적이지 않고 헷갈려서 `np.newaxis`를 만들었다.  
numpy를 만들 때 python의 모든 연산자를 다 사용해서 남는 연산자가 없었다. 그래서 `None`을 이용했다. 

In [108]:
a[None]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

### expand_dims

In [109]:
# 1번째 자리에 차원을 늘린다.
np.expand_dims(a, 1)

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

## indexer

소괄호() 대신 대괄호[]를 쓰는 것을 인덱서라고 한다. 

### r_

호출해보면 index_tricks라는 단어가 보인다.

In [112]:
np.r_

`r_`는 row로 array 두개를 붙여줬다.

In [115]:
np.r_[a, a]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
# r_은 다음과 같다. 
np.vstack((a,a))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### c_

`c_`는 column방향으로 array를 붙인다.

In [117]:
np.c_[a,a]

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [118]:
# c_은 다음과 같다. 
np.hstack((a,a))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [119]:
# 이런 방법도 있다. 
np.column_stack((a,a))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

### s_

In [50]:
# s_는 슬라이싱에 관련된 기능인데 조금 복잡하다.
np.s_

## ix_

`ix_`는 \_가 붙었지만 indexer가 아니다. 대괄호[]가 아니라 소괄호()를 쓴다. (혼동 주의)

In [145]:
np.ix_()

()

In [147]:
np.ix_([1,2], [1,2])

(array([[1],
        [2]]), array([[1, 2]]))

In [148]:
a, b = np.ix_([1,2], [1,2])

In [149]:
a

array([[1],
       [2]])

In [150]:
b

array([[1, 2]])

In [151]:
# broadcasting
a + b

array([[2, 3],
       [3, 4]])

## array 한줄로 펴기

### flatten

In [51]:
a = np.arange(12).reshape(3,4)

In [52]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
b = a.flatten() # copy

In [54]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

`flatten`은 copy 개념이다.  
b를 바꿔도 a는 그대로이다.

In [140]:
b[0] = 100

In [141]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### ravel

In [142]:
b = a.ravel() # 라벨 = 볼레로(뷰)

In [55]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

`ravel`은 view 개념이다.  
b를 바꾸면 a도 바뀐다.

In [143]:
b[0] = 200

In [144]:
a

array([[200,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

## 전치(차원 교환)

numpy에서 계산의 기본은 모양 맞추기이다.  
모양을 맞추기 위해서 전치는 중요하다.

### T

In [154]:
a

array([[1],
       [2]])

In [155]:
a.T

array([[1, 2]])

### transpose

`.T`는 `transpose(array, axes=None)`와 같다.

In [156]:
np.transpose(a)

array([[1, 2]])

### swapaxes

In [159]:
# a의 0번 차원과 1번 차원을 바꾼다.
np.swapaxes(a, 0, 1)

array([[1, 2]])

## structured array

- 빅데이터 분석/ 기계학습 전처리 / pandas의 기초
- 우리만의 데이터 타입을 만들 수 있다. 
- [공식문서 참고](https://numpy.org/doc/stable/user/basics.rec.html)

In [62]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]) # dtype은 (이름, 데이터타입)을 튜플로 묶는다.

In [63]:
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

structured array는 이름으로 데이터에 접근할 수 있다.

In [ ]:
# Error
# 이름을 메소드 방식으로 데이터에 접근할 수 없다.
x.name

In [66]:
# 이름을 딕셔너리 방식으로 데이터에 접근할 수 있다. 
x["name"] 

array(['Rex', 'Fido'], dtype='<U10')

In [67]:
x["age"]

array([9, 3])

인덱싱도 가능하다. 

In [165]:
x[0] # 복잡한 데이터 구조를 활용할 수 있다. 

('Rex', 9, 81.)

fancy indexing도 가능하다. 

In [69]:
x[[0]] 

array([('Rex', 9, 81.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

dtype에 대해서 알아보자

In [68]:
x.dtype

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [70]:
dir(x.dtype)

['__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'alignment',
 'base',
 'byteorder',
 'char',
 'descr',
 'fields',
 'flags',
 'hasobject',
 'isalignedstruct',
 'isbuiltin',
 'isnative',
 'itemsize',
 'kind',
 'metadata',
 'name',
 'names',
 'ndim',
 'newbyteorder',
 'num',
 'shape',
 'str',
 'subdtype',
 'type']

In [176]:
# names는 dtype에서 이름만 뽑아온다.
x.dtype.names

('name', 'age', 'weight')

이름으로 fancy indexing은 안된다.

In [ ]:
# Error
x[x.dtype.names]

In [181]:
# 이름 하나로 불러오는 것은 가능하다.
x["age"]

array([9, 3])

`descr`은 이름과 데이터 타입을 동시에 알려준다. 

In [177]:
x.dtype.descr

[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')]

### pandas는 structured array와 비슷하다.

In [167]:
import seaborn as sns

In [168]:
iris = sns.load_dataset("iris")

In [169]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

pandas는 내부구조가  numpy 이다.   
`values` 메소드는 데이터를 numpy로 돌려준다.

In [171]:
iris.values

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.6, 1.4, 0.2, 'setosa'],
       [5.4, 3.9, 1.7, 0.4, 'setosa'],
       [4.6, 3.4, 1.4, 0.3, 'setosa'],
       [5.0, 3.4, 1.5, 0.2, 'setosa'],
       [4.4, 2.9, 1.4, 0.2, 'setosa'],
       [4.9, 3.1, 1.5, 0.1, 'setosa'],
       [5.4, 3.7, 1.5, 0.2, 'setosa'],
       [4.8, 3.4, 1.6, 0.2, 'setosa'],
       [4.8, 3.0, 1.4, 0.1, 'setosa'],
       [4.3, 3.0, 1.1, 0.1, 'setosa'],
       [5.8, 4.0, 1.2, 0.2, 'setosa'],
       [5.7, 4.4, 1.5, 0.4, 'setosa'],
       [5.4, 3.9, 1.3, 0.4, 'setosa'],
       [5.1, 3.5, 1.4, 0.3, 'setosa'],
       [5.7, 3.8, 1.7, 0.3, 'setosa'],
       [5.1, 3.8, 1.5, 0.3, 'setosa'],
       [5.4, 3.4, 1.7, 0.2, 'setosa'],
       [5.1, 3.7, 1.5, 0.4, 'setosa'],
       [4.6, 3.6, 1.0, 0.2, 'setosa'],
       [5.1, 3.3, 1.7, 0.5, 'setosa'],
       [4.8, 3.4, 1.9, 0.2, 'setosa'],
       [5.0, 3.0, 1.6, 0.

pandas도 structured array처럼 dictionary 방식으로 값을 뽑아낼 수 있다. 

In [172]:
iris["sepal_length"] 

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

structured array는 복잡하게 혼합되어 있는 데이터를 빠르게 처리할 수 있다. 

## 파일

### 2가지 종류의 파일 형태

- 사람 기준 (text)
- 기계 기준 (binary)

In [189]:
%%writefile sun.txt
aasilufnlksajdnfliuawnefjknjkn
asdliukabnlskjdfna
asidllnbwkenafliabsfuhbewu

Overwriting sun.txt


### 파일의 요소는 3가지

- 파일 경로 (생략 가능, 현재 위치)
- 파일 이름
- 파일 확장자 (생략 가능)

### open

python에서 파일을 읽어오는 기능은 기본적으로 `open` 뿐이다.

In [190]:
open('sun.txt')

<_io.TextIOWrapper name='sun.txt' mode='r' encoding='cp949'>

In [191]:
a = open('sun.txt')

처음보면 `dir`부터 한다.  
메서드를 보고 객체의 성질을 파악할 수 있다.

In [188]:
# __enter__와 __exit__는 짝이다.
# __next__는 iteration에 쓸 수 있다. 
dir(a)

['_CHUNK_SIZE',
 '__class__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_checkClosed',
 '_checkReadable',
 '_checkSeekable',
 '_checkWritable',
 '_finalizing',
 'buffer',
 'close',
 'closed',
 'detach',
 'encoding',
 'errors',
 'fileno',
 'flush',
 'isatty',
 'line_buffering',
 'mode',
 'name',
 'newlines',
 'read',
 'readable',
 'readline',
 'readlines',
 'reconfigure',
 'seek',
 'seekable',
 'tell',
 'truncate',
 'writable',
 'write',
 'write_through',
 'writelines']

`"wb"`는 write + binary의 줄임 표현이다.  
쓰기 모드로 파일을 불러오며, binary로 쓴다는 뜻이다.

In [193]:
b = open("moon.txt", "wb")

binary 모드이기 때문에 binary 타입으로 입력해야한다.

In [ ]:
# Error
# str은 binary가 아니기 때문이다.
b.write('abc')

In [195]:
# binary 문자열을 써야한다. 
b.write(b'abc')

3

`open`을 사용한 다음에는 반드시 `close`한다.

In [196]:
b.close()

저장한 moon.txt를 불러온다.

In [197]:
c = open("moon.txt")

`__next__`가 있기 때문에 `next`를 쓸 수 있다. 

In [199]:
# binary로 저장했는데 text로 읽어왔다.
next(c)

'abc'

확장자를 txt가 아닌 임의의 확장자를 사용해도 상관 없다.

In [205]:
b = open("moon.abc", "wb")

In [206]:
# binary 타입인 bytes
b.write(b"aaaa") 

4

In [207]:
# 사용 후에는 close
b.close() 

In [208]:
# 다시 읽기 모드로 불러들임
c = open("moon.abc") 

In [209]:
# 이번에도 text로 읽어왔다.
next(c) 

'aaaa'

### with

In [210]:
with open('moon.bb', 'wb') as b:
    b.write(b"ttt")
    b.write(b"aaa")

`with` 구문은 시작할 때 `__enter__`를, 종료될 때 `__exit__`을 자동으로 실행해준다.  
이미 `__exit__`가 실행되었기 때문에 closed file이라는 에러가 발생한다.

In [212]:
# Error
# closed file
b.write(b"abc")

ValueError: write to closed file

`open`은 모든 파일을 text로 읽는다.  

In [213]:
%%writefile num.txt
1, 2, 3, 4, 5
6, 7, 8, 9, 10

Writing num.txt


In [215]:
# num.txt는 숫자로 저장했지만 문자열로 읽어온다.
with open('num.txt') as b:
    print(b.readlines())

['1, 2, 3, 4, 5\n', '6, 7, 8, 9, 10\n']


### pickle

python의 기본적인 파일
- text, binary 

객체의 의미를 보존하게 저장
- pickle

In [216]:
import pickle

In [217]:
a = np.array([1,2,3,4,5])

pickle로 객체 저장하는 방법은 다음과 같다.
- mode는 "wb"
- 확장자는 상관없음
- `dump` 메소드 사용

In [218]:
with open("x.nn", "wb") as f:
    pickle.dump(a, f)

pickle로 저장된 객체를 불러오는 방법은 다음과 같다. 
- mode는 "rb"
- `load`메소드 사용

In [219]:
with open("x.nn", "rb") as f:
    b = pickle.load(f)

`open`은 text로만 읽어오는 반면, `pickle`은 객체 그자체를 저장하고 불러온다.

In [220]:
b

array([1, 2, 3, 4, 5])

### numpy 파일 저장 & 불러오기

numpy 자체적으로 저장과 불러오는 기능을 지원한다.

In [72]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

array 객체 하나는 `save`로 저장할 수 있다.

In [231]:
np.save("t", a)

In [232]:
# 확장자는 자동으로 .npy가 붙는다.
c = np.load("t.npy")

In [233]:
c

array([1, 2, 3, 4, 5])

`savez`는 array 여러개를 저장할 수 있다.

In [234]:
np.savez('s', a, c)

In [73]:
# 확장자는 자동으로 .npz가 붙는다.
c = np.load("s.npz")

In [74]:
c

딕셔너리 방식으로 저장된 객체를 꺼낼 수 있다.

In [84]:
c.files

['arr_0', 'arr_1']

In [85]:
c["arr_0"]

array([1, 2, 3, 4, 5])

In [86]:
c["arr_1"]

array([1, 2, 3, 4, 5])

### numpy 텍스트 파일 읽기

### loadtxt

In [ ]:
# Error
np.loadtxt("num.txt")

```python
ValueError: could not convert string to float: '1,'
```

In [239]:
# delimiter는 구분자
# num.txt는 ,로 값이 구분되어 있다.
np.loadtxt("num.txt", delimiter=",")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

### genfromtxt

In [240]:
# loadtxt의 확장판
# Error를 일으키기보다는 nan으로 읽는다. 
np.genfromtxt("num.txt")

array([[nan, nan, nan, nan,  5.],
       [nan, nan, nan, nan, 10.]])

In [241]:
# delimiter를 쓰면 제대로 읽어온다.
np.genfromtxt("num.txt", delimiter=",")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

## 데이터를 OPEN(Translation)시켜서 시작

### pandas

- numpy : low -level
- pandas : high - level

In [242]:
import numpy as np
import pandas as pd

In [243]:
pd.__version__

'0.25.3'

In [244]:
np.__version__

'1.18.1'

pandas의 최신버전은 1버전대이다.  
0.2 버전대를 사용중이면 다음 코드로 업데이트한다. 

In [246]:
!pip install -U --user pandas

Requirement already up-to-date: pandas in c:\users\jinhyo\anaconda3\lib\site-packages (1.0.3)


In [2]:
# kernel restart
import numpy as np
import pandas as pd
pd.__version__

'1.0.3'

`read_csv`는 `loadtxt`, `genfromtxt`의 확장판이다.  
텍스트형태로 된 데이터를 정형데이터로 읽어온다.  
이름이 있으면 이름으로 읽어오고, 없으면 0부터 숫자를 붙인다. 

In [3]:
data = pd.read_csv("num.txt", header=None)

In [4]:
# DataFrame
data

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

`.values`하면 numpy 포맷으로 변환된다. 
내부적으로 numpy로 되어있기 때문에 가능하다. 

In [5]:
data.values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int64)

In [6]:
# 행과 열로 구성된 pandas 데이터 타입 : DataFrame
type(data)

pandas.core.frame.DataFrame

In [7]:
# __array__가 있으면 numpy와 호환된다.
dir(data)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_e

웹주소에서 데이터를 불러올 수도 있다. 

In [8]:
data = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [9]:
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

pandas는 데이터를 메모리에 올려서 사용한다.
- 컴퓨터 메모리가 클수록 큰 파일 사용할 수 있다. 
- 메모리에 올리기 때문에 처리 속도가 빠르다. 

In [10]:
# memory usage
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


공공데이터 포털에서 데이터를 받아서 pandas로 직접 빅데이터 처리할 수 있다.

[실습 데이터 링크](https://www.data.go.kr/data/15012186/fileData.do)

파일명은 펴의상 ttt로 바꾸었다.

In [ ]:
# UnicodeDecodeError 
data = pd.read_csv("ttt.csv") 

UnicodeDecodeError는 인코딩 문제이다. encoding 옵션으로 해결 가능하다.

키워드인자로 데이터 불러올때 여러가지 옵션 지정할 수 있다.

In [12]:
data = pd.read_csv("ttt.csv", encoding="cp949")

In [13]:
data

보안등위치명  설치개수                 소재지도로명주소  소재지지번주소  위도  경도  설치년도  설치형태  \
0      전농1동-0001     1       서울특별시 동대문구 왕산로 292      NaN NaN NaN   NaN   NaN   
1      전농1동-0002     1     서울특별시 동대문구 왕산로 294-1      NaN NaN NaN   NaN   NaN   
2      전농1동-0003     1       서울특별시 동대문구 왕산로 302      NaN NaN NaN   NaN   NaN   
3      전농1동-0004     1     서울특별시 동대문구 왕산로 306-3      NaN NaN NaN   NaN   NaN   
4      전농1동-0005     1    서울특별시 동대문구 왕산로 306-10      NaN NaN NaN   NaN   NaN   
...          ...   ...                      ...      ...  ..  ..   ...   ...   
11095  이문2동-0556     1    서울특별시 동대문구 한천로33가길 22      NaN NaN NaN   NaN   NaN   
11096  이문2동-0557     1        서울특별시 동대문구 18-3 앞      NaN NaN NaN   NaN   NaN   
11097  이문2동-0558     1        서울특별시 동대문구 이문로162      NaN NaN NaN   NaN   NaN   
11098  이문2동-0559     1  서울특별시 동대문구 신이문로25길 18-1      NaN NaN NaN   NaN   NaN   
11099  이문2동-0827     1    서울특별시 동대문구 이문로34길 43       NaN NaN NaN   NaN   NaN   

           관리기관전화번호        관리기관명     데이터기준일자  
0      02-2127-4832  서울특별시 동대문구청  2020-04-28  
1      02-2127-4832  서울특별시 동대문구청  2020-04-28  
2      02-2127-4832  서울특별시 동대문구청  2020-04-28  
3      02-2127-4832  서울특별시 동대문구청  2020-04-28  
4      02-2127-4832  서울특별시 동대문구청  2020-04-28  
...             ...          ...         ...  
11095  02-2127-4832  서울특별시 동대문구청  2020-04-28  
11096  02-2127-4832  서울특별시 동대문구청  2020-04-28  
11097  02-2127-4832  서울특별시 동대문구청  2020-04-28  
11098  02-2127-4832  서울특별시 동대문구청  2020-04-28  
11099  02-2127-4832  서울특별시 동대문구청  2020-04-28  

[11100 rows x 11 columns]

`.values`로 numpy로 바로 바꿀 수 있다.

In [14]:
data.values

array([['전농1동-0001', 1, '서울특별시 동대문구 왕산로 292', ..., '02-2127-4832',
        '서울특별시 동대문구청', '2020-04-28'],
       ['전농1동-0002', 1, '서울특별시 동대문구 왕산로 294-1', ..., '02-2127-4832',
        '서울특별시 동대문구청', '2020-04-28'],
       ['전농1동-0003', 1, '서울특별시 동대문구 왕산로 302', ..., '02-2127-4832',
        '서울특별시 동대문구청', '2020-04-28'],
       ...,
       ['이문2동-0558', 1, '서울특별시 동대문구 이문로162', ..., '02-2127-4832',
        '서울특별시 동대문구청', '2020-04-28'],
       ['이문2동-0559', 1, '서울특별시 동대문구 신이문로25길 18-1', ..., '02-2127-4832',
        '서울특별시 동대문구청', '2020-04-28'],
       ['이문2동-0827', 1, '서울특별시 동대문구 이문로34길 43 ', ..., '02-2127-4832',
        '서울특별시 동대문구청', '2020-04-28']], dtype=object)