<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#numpy" data-toc-modified-id="numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>numpy</a></span><ul class="toc-item"><li><span><a href="#numpy-값-만들기" data-toc-modified-id="numpy-값-만들기-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>numpy 값 만들기</a></span><ul class="toc-item"><li><span><a href="#np.array" data-toc-modified-id="np.array-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>np.array</a></span></li><li><span><a href="#np.zeros" data-toc-modified-id="np.zeros-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>np.zeros</a></span></li><li><span><a href="#np.eye" data-toc-modified-id="np.eye-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>np.eye</a></span></li><li><span><a href="#np.identity" data-toc-modified-id="np.identity-1.1.4"><span class="toc-item-num">1.1.4&nbsp;&nbsp;</span>np.identity</a></span></li><li><span><a href="#np.full" data-toc-modified-id="np.full-1.1.5"><span class="toc-item-num">1.1.5&nbsp;&nbsp;</span>np.full</a></span></li><li><span><a href="#np.empty" data-toc-modified-id="np.empty-1.1.6"><span class="toc-item-num">1.1.6&nbsp;&nbsp;</span>np.empty</a></span></li><li><span><a href="#_like" data-toc-modified-id="_like-1.1.7"><span class="toc-item-num">1.1.7&nbsp;&nbsp;</span>_like</a></span></li><li><span><a href="#np.linspace" data-toc-modified-id="np.linspace-1.1.8"><span class="toc-item-num">1.1.8&nbsp;&nbsp;</span>np.linspace</a></span></li><li><span><a href="#np.logspace" data-toc-modified-id="np.logspace-1.1.9"><span class="toc-item-num">1.1.9&nbsp;&nbsp;</span>np.logspace</a></span></li></ul></li><li><span><a href="#dtype" data-toc-modified-id="dtype-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>dtype</a></span></li><li><span><a href="#order" data-toc-modified-id="order-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>order</a></span></li><li><span><a href="#array의-정보" data-toc-modified-id="array의-정보-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>array의 정보</a></span><ul class="toc-item"><li><span><a href="#shape" data-toc-modified-id="shape-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>shape</a></span></li><li><span><a href="#ndim" data-toc-modified-id="ndim-1.4.2"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>ndim</a></span></li><li><span><a href="#size" data-toc-modified-id="size-1.4.3"><span class="toc-item-num">1.4.3&nbsp;&nbsp;</span>size</a></span></li><li><span><a href="#dtype" data-toc-modified-id="dtype-1.4.4"><span class="toc-item-num">1.4.4&nbsp;&nbsp;</span>dtype</a></span></li><li><span><a href="#itemsize" data-toc-modified-id="itemsize-1.4.5"><span class="toc-item-num">1.4.5&nbsp;&nbsp;</span>itemsize</a></span></li><li><span><a href="#data" data-toc-modified-id="data-1.4.6"><span class="toc-item-num">1.4.6&nbsp;&nbsp;</span>data</a></span></li></ul></li><li><span><a href="#numpy와-python의-속도차이" data-toc-modified-id="numpy와-python의-속도차이-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>numpy와 python의 속도차이</a></span></li></ul></li><li><span><a href="#copy" data-toc-modified-id="copy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>copy</a></span><ul class="toc-item"><li><span><a href="#python에서-copy" data-toc-modified-id="python에서-copy-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>python에서 copy</a></span><ul class="toc-item"><li><span><a href="#mutable" data-toc-modified-id="mutable-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>mutable</a></span></li><li><span><a href="#copy" data-toc-modified-id="copy-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>copy</a></span></li><li><span><a href="#shallow-copy" data-toc-modified-id="shallow-copy-2.1.3"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>shallow copy</a></span></li><li><span><a href="#deepcopy" data-toc-modified-id="deepcopy-2.1.4"><span class="toc-item-num">2.1.4&nbsp;&nbsp;</span>deepcopy</a></span></li></ul></li><li><span><a href="#numpy의-copy" data-toc-modified-id="numpy의-copy-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>numpy의 copy</a></span><ul class="toc-item"><li><span><a href="#mutable" data-toc-modified-id="mutable-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>mutable</a></span></li><li><span><a href="#deepcopy" data-toc-modified-id="deepcopy-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>deepcopy</a></span></li></ul></li></ul></li><li><span><a href="#다른-데이터-타입에서-데이터-가져오기" data-toc-modified-id="다른-데이터-타입에서-데이터-가져오기-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>다른 데이터 타입에서 데이터 가져오기</a></span><ul class="toc-item"><li><span><a href="#as-계열" data-toc-modified-id="as-계열-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>as 계열</a></span></li><li><span><a href="#from-계열" data-toc-modified-id="from-계열-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>from 계열</a></span></li></ul></li><li><span><a href="#값-뽑기" data-toc-modified-id="값-뽑기-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>값 뽑기</a></span><ul class="toc-item"><li><span><a href="#1.-comma로-값-뽑기" data-toc-modified-id="1.-comma로-값-뽑기-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>1. comma로 값 뽑기</a></span></li><li><span><a href="#2.-boolean-indexing" data-toc-modified-id="2.-boolean-indexing-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>2. boolean indexing</a></span></li></ul></li><li><span><a href="#to-be-continue..." data-toc-modified-id="to-be-continue...-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>to be continue...</a></span></li></ul></div>

# [AI 오픈 이노베이션] 기본 저녁반<a class="tocSkip">
GitHub link: [https://github.com/realblack0/8th_ai_lecture_fundamental](https://github.com/realblack0/8th_ai_lecture_fundamental)  
E-Mail: realblack0@gmail.com

## numpy

In [1]:
import numpy as np

In [3]:
a = np.zeros(3)

In [4]:
# array는 n차원의 대표격
a

array([0., 0., 0.])

처음보면 `type`와 `dir`해본다.

In [5]:
type(a)

numpy.ndarray

In [6]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

### numpy 값 만들기

값을 생성하는 방법:
- literal
    - 기본적으로 기본 자료형만 지원된다.
    - 메타클래스를 이용해서 리터럴을 만들 수는 있다.
- Class Instance
- Factory Method

numpy는 Factory Method 방법을 더 많이 사용한다.

#### np.array

In [7]:
# 1차원
a = np.array([1,2,3,4])

In [8]:
a

array([1, 2, 3, 4])

In [9]:
# 2차원
b = np.array([[1,2], [2,3]])

In [10]:
b

array([[1, 2],
       [2, 3]])

파이썬의 기본 라이브러리에도 array가 있다.  

python의 array와 numpy의 **공통점**
- array란 data structure를 기본으로 한다.

**차이점**
- numpy는 C를 기반으로 만들어졌고 vectorization을 지원한다.
- numpy가 비교적 사용하기 쉽고 더 많은 기능을 지원한다. 
- numpy는 C로 만들었기 때문에 시스템을 탄다. 
    - 실행이 조금씩 다르다. (임베디드 등)

In [11]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
a = np.array(['1', 2, 3])

In [12]:
# numpy는 homogeneous
a

array(['1', '2', '3'], dtype='<U1')

numpy는 문자열 데이터 뿐만 아니라 시간관련된 데이터도 지원하는데,  
우리의 관심사는 주로 숫자형이다.

#### np.zeros

In [14]:
# tuple로 인자를 넣으면 그대로 모양을 만든다.
# (2,3) -> 2행 3열 행렬 만들기
# zeros는 0으로 값을 모두 채운다. 

a = np.zeros((2,3))

In [15]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# 튜플 대신 숫자를 넣으면 벡터로 만든다. 
# dtype의 기본값이 float이므로 0.로 보인다.
a = np.zeros(4)

In [17]:
a

array([0., 0., 0., 0.])

#### np.eye

In [18]:
# eye는 단위행렬
# 숫자만 쓸 수 있다. 
b = np.eye(3)

In [19]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### np.identity

In [21]:
# 수학에서 단위행렬은 영어로 identity matrix
# 알고 있는 이름을 그대로 사용하는 경우가 많다.
b = np.identity(3)

In [22]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
# eye는 랭크 개념도 쓸 수 있다.
# identity와 거의 같지만 조금 다른 점이 있다. 
b = np.eye(3, k=2)

In [44]:
b

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### np.full

In [39]:
# 내가 정한 값으로 채운다.
x = np.full((2,2), 6)

In [40]:
x

array([[6, 6],
       [6, 6]])

#### np.empty

In [86]:
# random (garbage) 값이 들어간다.
# C의 garbage 개념 사용됨
a = np.empty((3,4))

In [87]:
a

array([[1.11915038e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [6.23047502e-307, 8.75983079e+164, 7.73900396e-091,
        6.23367033e+174],
       [1.29078601e+160, 9.51332803e+169, 3.99910963e+252,
        3.46683565e+179]])

#### \_like

In [90]:
# _like가 붙으면 shape이 같게 만들어준다.
# 연산하기 위해서 shape을 맞춰야하는 경우가 많다.

b = np.ones((3,4))
a = np.empty_like(b)

In [91]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
a = np.ones_like(b)

In [93]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

numpy는 ndarray의 shape이 맞지 않으면 연산이 안된다.  
numpy에서는 shape이 아주 중요하다.

In [2]:
a = np.array([[1,2,3], [4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b = np.eye(2)

In [5]:
b

array([[1., 0.],
       [0., 1.]])

In [26]:
# Error
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

#### np.linspace

In [109]:
# 등간격으로 값을 생성해준다.

a = np.linspace(0, 49) # defalut num=50
                       # 0에서 49까지

In [110]:
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

####  np.logspace

In [114]:
# linspace와 비슷하다.
# log scale을 사용하는 차이

a = np.logspace(1, 50, 10)  # default num 대신 10 사용
                            # 0에서 50까지

In [119]:
a

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

---

실제 tensorflow에서도 array를 사용한다.  
array는 앞으로 계속 사용한다.

In [35]:
import tensorflow as tf

In [36]:
x = tf.keras.datasets.mnist.load_data()

In [37]:
# array
x[0][0]

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [38]:
# 3차원
x[0][0].shape

(60000, 28, 28)

### dtype

numpy는 C를 기반으로 만들었기 때문에 C의 데이터 타입을 차용할 수 있다. 

In [45]:
a = np.array([1,2,3], dtype=np.int8)

In [46]:
a

array([1, 2, 3], dtype=int8)

In [47]:
# 8bit 정수형으로 표현가능한 값(256)을 초과하면 overflow
# overflow 에러를 내는 대신에 값의 범위를 한정시킨다.
a = np.array([267,2,3], dtype=np.int8)

In [48]:
a

array([11,  2,  3], dtype=int8)

In [56]:
# int16은 267을 표현할 수 있다.
a = np.array([267,2,3], dtype=np.int16)

In [57]:
a

array([267,   2,   3], dtype=int16)

In [66]:
# int는 python의 int를 사용하는 것이다.
a = np.array([267,2,3], dtype=int)

In [67]:
a

array([267,   2,   3])

In [68]:
# 문자열 표현으로 쓸 수 있다.
# i8 = int64
a = np.array([267, 2, 3], dtype="i8")

In [69]:
a

array([267,   2,   3], dtype=int64)

In [70]:
a.dtype

dtype('int64')

### order

`np.array`의 parameter를 보면 `order`가 있다.  

order
- C: C방식으로 데이터 저장 (행기준)
    - 예시: $\array{1 \ 2 \ 3 \\ 4 \ 5 \ 6 }$
- F: Fascal, Fortran 방식으로 데이터 저장 (열기준)
    - 예시: $\array{1 \ 3 \ 5 \\ 2 \ 4 \ 6 }$
- A: Auto
- K: don't care 

우리는 C방식을 쓸 것이다. 

### array의 정보 

numpy 공식문서 참고: https://docs.scipy.org/doc/numpy/user/quickstart.html

In [72]:
# numpy의 도움말 함수
np.lookfor("sum")

Search results for 'sum'
------------------------
numpy.sum
    Sum of array elements over a given axis.
numpy.cumsum
    Return the cumulative sum of the elements along a given axis.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nansum
    Return the sum of array elements over a given axis treating Not a
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.einsum_path
    Evaluates the lowest cost contraction order for an einsum expression by
numpy.trace
    Return the sum along diagonals of the array.
numpy.ma.sum
    Return the sum of the array elements over the given axis.
numpy.polyadd
    Find the sum of two polynomials.
numpy.ma.cumsum
    Return the cumulative sum of the array elements over the given axis.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.matrix.sum
    Returns the sum of the matrix elements, along the given axis.
numpy.logaddexp2
    Logarit

In [73]:
a = np.array([[1,2,3], [4,5,6]])

#### shape

In [76]:
# array의 shape을 알려준다.
a.shape

(2, 3)

#### ndim

In [77]:
# 몇 차원인지 한번에 알 수 있다.
# shape만 있으면 알 수 있다.
a.ndim

2

#### size

In [80]:
# 원소 개수를 알려준다.
# shape만 있으면 알 수 있다. 
a.size

6

#### dtype

In [74]:
a.dtype

dtype('int32')

#### itemsize

In [75]:
# 원소당 byte수를 알려준다.
# dtype을 8로 나누면 itemsize가 된다. dtype만 있으면 알 수 있다.
a.itemsize

4

#### data

In [78]:
# memoryview
a.data

In [83]:
a.data.obj

array([[1, 2, 3],
       [4, 5, 6]])

### numpy와 python의 속도차이

값이 작을 때는 속도가 비슷하다.

In [101]:
%time np.sum(np.arange(10000))

Wall time: 0 ns


49995000

In [102]:
%time sum(range(10000))

Wall time: 0 ns


49995000

값이 커지면 속도차이가 커진다.

In [103]:
%time np.sum(np.arange(100000000)) # overflow때문에 결과값은 좀 다르지만 차치한다.

Wall time: 330 ms


887459712

In [104]:
%time sum(range(100000000))

Wall time: 4.37 s


4999999950000000

같은 np.sum을 써도 numpy로 값을 만들었을 때가 더 빠르다.

In [105]:
%time np.sum(np.arange(100000000))

Wall time: 322 ms


887459712

In [106]:
%time np.sum(range(100000000))

Wall time: 18.3 s


887459712

## copy

※ 대입문 6가지
```python
a = 1
a = b = 1 # mutable일 때 조심해야 한다.
a, b = 1, 2
a, *b = 1, 2, 3
a += 1
global, nonlocal
```

### python에서 copy

#### mutable

In [135]:
a = [1,2,3]

In [136]:
b = a

In [137]:
b[0] = 7

In [138]:
# a도 바뀐다. 
# a와 b는 메모리를 공유하기 때문이다.
a

[7, 2, 3]

#### copy

In [139]:
a = [1,2,3]

In [140]:
# copy는 똑같은 값만 가지고 메모리는 공유하지 않는다.
b = a.copy()

In [141]:
b[0] = 7

In [142]:
# a는 안 바뀐다. 
a

[1, 2, 3]

#### shallow copy

In [147]:
a = [[1,2,3]]

In [148]:
b = a.copy()

In [149]:
b[0][0] = 7

In [150]:
# copy를 했는데도 a도 바뀐다.
# shallow copy
a

[[7, 2, 3]]

#### deepcopy

In [151]:
import copy

In [152]:
a = [[1,2,3]]

In [153]:
b = copy.deepcopy(a)

In [154]:
b[0][0] = 7

In [155]:
# deep copy
# deepcopy는 안 바뀐다.
a

[[1, 2, 3]]

`[:]`는 전체라는 뜻이다.  
슬라이싱 방식으로 재할당하면 deepcopy가 된다.

In [168]:
a = [1,2,3]

In [169]:
b = a[:]

In [170]:
b[0] = 7

In [171]:
a

[1, 2, 3]

※ python의 copy는 기본적으로 shallow copy이다.

### numpy의 copy

In [123]:
a = b = np.array([1,2,3])

array는 sequence 타입이므로 인덱싱과 슬라이싱 가능하다.

In [173]:
a[0]

1

In [174]:
a[:]

[1, 2, 3]

numpy는 mutable이다.  
예외가 몇가지 있지만 mutable에 더 가깝다. 

In [175]:
a[0] = 100

In [176]:
a

[100, 2, 3]

#### mutable

In [181]:
a = np.array([[1,2,3]])

In [182]:
b = a

In [183]:
b[0][0] = 100

In [184]:
# a 값 바뀌었다.
a

array([[100,   2,   3]])

#### deepcopy

In [186]:
a = np.array([[1,2,3]])

In [187]:
# numpy는 기본적으로 deepcopy이다.
b = a.copy()

In [188]:
b[0][0] = 100

In [189]:
a

array([[1, 2, 3]])

## 다른 데이터 타입에서 데이터 가져오기

as계열과 from계열을 사용할 때는 mutable을 조심해야한다. 

### as 계열

다른 데이터 타입을 가져와서 바꿔서 사용할 때 as라는 이름이 보통 붙는다.

In [191]:
# python의 데이터 타입을 가져와서 ndarray로 변환
np.asarray([1,2,3])

array([1, 2, 3])

In [190]:
# python의 데이터 타입을 가져와서 float ndarray로 변환
np.asfarray([1,2,3])

array([1., 2., 3.])

### from 계열

numpy의 as계열과 from계열은 약간 비체계적인 면이 있기 때문에 tensorflow에서는 조금 다르게 사용한다.

---

**※ numpy에서 데이터 만드는 방법 정리**
- 생성
    - factory method 계열
- 기반
    - array, as 계열, from 계열, _like 계열
- load
    - 파일로부터 값을 가져오는 방법

## 값 뽑기

### 1. comma로 값 뽑기

In [7]:
a = [[1,2,3], [4,5,6]]           # python
b = np.array([[1,2,3], [4,5,6]]) # numpy

python은 인덱싱/슬라이싱할 때 comma 사용할 수 없다.

In [ ]:
# Error
a[0, -1]

슬라이스 객체를 이용해서 comma를 사용하는 방법은 있다.

In [8]:
a[slice(0,1)]

[[1, 2, 3]]

이외에도 metaclass로 가능하게 만드는 방법도 있지만 기본적으로는 안된다.

numpy는 기본적으로 인덱싱/슬라이싱할 때 comma를 사용할 수 있다.

In [194]:
b[0, -1]

3

### 2. boolean indexing

In [198]:
b = np.array([[1,2,3,4]])

In [199]:
b

array([[1, 2, 3, 4]])

array를 scalar와 연산하면 elementwise로 계산한다. (elementwise : 원소별로 각각 계산)

In [202]:
# 원소별로 비교해서 True/False 로 바꾼다.
b > 2

array([[False, False,  True,  True]])

numpy는 indexing, slicing 자리에 조건도 쓸 수 있다.  
True에 해당하는 값만 뽑아준다.

In [203]:
b[b>2]

array([3, 4])

python format의 True/False는 boolean indexing이 안된다. 

In [204]:
# Error
b[[[True,True, False, False]]]

C:\Users\JINHYO\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 4

numpy에서 boolean indexing의 조건
- array만 된다.
- numpy True, False로만 구성되어야한다.
- shape이 맞아야 한다. 
- 개수가 맞을때만 사용할 수 있다.

In [205]:
b[np.array([[True,True, False, False]])]

array([1, 2])

In [11]:
# python bool과 다름
np.array([[True,True, False, False]]).dtype

dtype('bool')

## to be continue...

값 뽑는 방법에 대하여 나머지는 다음시간에 이어서 계속