In [1]:
import numpy as np

In [2]:
a = np.zeros(3)

In [3]:
a

array([0., 0., 0.])

In [4]:
type(a)

numpy.ndarray

In [5]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [6]:
a = np.array([1,2,3])

In [7]:
a

array([1, 2, 3])

In [9]:
b = np.array([[1,2],[2,3]])

In [10]:
b

array([[1, 2],
       [2, 3]])

In [11]:
a = np.array(['1',2,3])

In [13]:
a ## 넘파이는 기본적으로 호모지니어스임

array(['1', '2', '3'], dtype='<U1')

In [14]:
a = np.zeros((2,3))

In [15]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
b = np.ones((3,2))

In [17]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
c = np.identity(3)

In [21]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
x = np.full((2,2),6)

In [23]:
x

array([[6, 6],
       [6, 6]])

In [24]:
a = np.array([267,2,3], dtype=np.int8)

In [25]:
a

array([11,  2,  3], dtype=int8)

In [28]:
a = np.array([[1,2,3],[1,2,3]])

In [29]:
a.dtype

dtype('int32')

In [30]:
a.data.obj

array([[1, 2, 3],
       [1, 2, 3]])

In [31]:
a = np.empty((3,4))

In [32]:
a

array([[8.18097385e-312, 2.86558075e-322, 0.00000000e+000,
        0.00000000e+000],
       [7.56599806e-307, 3.76231868e+174, 4.95916193e-090,
        1.32677925e-075],
       [5.54463467e+169, 6.03178602e+174, 6.48224659e+170,
        5.82471487e+257]])