<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Tensor와-numpy" data-toc-modified-id="Tensor와-numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Tensor와 numpy</a></span><ul class="toc-item"><li><span><a href="#tensor-만들기" data-toc-modified-id="tensor-만들기-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>tensor 만들기</a></span></li><li><span><a href="#tensor-정보" data-toc-modified-id="tensor-정보-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>tensor 정보</a></span></li><li><span><a href="#tensor-연산" data-toc-modified-id="tensor-연산-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>tensor 연산</a></span></li><li><span><a href="#GPU-지원" data-toc-modified-id="GPU-지원-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>GPU 지원</a></span></li></ul></li><li><span><a href="#Dataset" data-toc-modified-id="Dataset-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Dataset</a></span><ul class="toc-item"><li><span><a href="#from" data-toc-modified-id="from-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>from</a></span></li><li><span><a href="#tfds" data-toc-modified-id="tfds-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>tfds</a></span></li><li><span><a href="#연습" data-toc-modified-id="연습-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>연습</a></span></li></ul></li></ul></div>

# [AI 오픈 이노베이션] 기본 저녁반<a class="tocSkip">
GitHub link: [https://github.com/realblack0/8th_ai_lecture_fundamental](https://github.com/realblack0/8th_ai_lecture_fundamental)  
E-Mail: realblack0@gmail.com

## Tensor와 numpy

이번 수업은 Tensorflow 공식 튜토리얼 [텐서와 연산](https://www.tensorflow.org/tutorials/customization/basics?hl=ko)을 참조하여 진행하였습니다.

tensor는 numpy의 array와 비슷하다.

In [1]:
import numpy as np
import tensorflow as tf
# tf.debugging.set_log_device_placement(True)

### tensor 만들기

tensor도 numpy처럼 값을 만드는 방법으로 factory method를 사용한다.

In [2]:
a = np.array([1,2,3])

In [3]:
aa = tf.constant([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
# numpy보다 보여주는 정보가 더 많다.
# numpy를 기반으로 만들어졌기 때문에 numpy라고 보인다.
aa

<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [35]:
# numpy를 기반으로 만들었기 때문에 쉽게 numpy로 바꿀 수 있다.
aa.numpy()

array([1, 2, 3])

`zeros`, `ones`, `zeros_like`, `ones_like` 모두 numpy와 같은 방식으로 tensor를 만드는 함수이다.

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
tf.zeros((2,3))

<tf.Tensor: id=3, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

numpy에서는 `full`이었는데, tensor에서는 `fill`이다.

numpy에서 용어가 애매한 것들을 tensor에서는 바로잡았기 때문에 약간의 차이가 있다.

In [8]:
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [9]:
tf.fill((2,3), 5)

<tf.Tensor: id=6, shape=(2, 3), dtype=int32, numpy=
array([[5, 5, 5],
       [5, 5, 5]])>

numpy에서 사용하는 기능 대부분 tensor에서 사용할 수 있다.

In [13]:
# 단위행렬을 만드는 eye
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
tf.eye(3)

<tf.Tensor: id=15, shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

numpy와 이름은 같지만, 기능이 다른 경우도 있다.

In [15]:
# numpy에서 identity는 단위행렬을 만든다.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# tensor에서 identity는 동일한 객체를 만들어준다.
# aa와 같은 객체 만든다.
tf.identity(aa)

<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [18]:
aa

<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

### tensor 정보

In [23]:
dir(aa)

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_add_consumer',
 '_as_node_def_i

numpy처럼 `shape`, `dtype`, `ndim`으로 배열 정보를 알 수 있다.

In [26]:
aa.shape

TensorShape([3])

In [27]:
aa.dtype

tf.int32

In [25]:
aa.ndim

1

In [24]:
# tensor는 numpy와 달리 GPU를 지원하므로, device로 어느 장치에 로드되어 있는지 알 수 있다. 
aa.device

'/job:localhost/replica:0/task:0/device:CPU:0'

### tensor 연산

numpy와 마찬가지로 element-wise로 연산한다.

In [30]:
np.add(a, a)

array([2, 4, 6])

In [29]:
tf.add(aa, aa)

<tf.Tensor: id=18, shape=(3,), dtype=int32, numpy=array([2, 4, 6])>

numpy와 마찬가지로 universal func이다.

In [32]:
np.add(3, 4)

7

In [31]:
tf.add(3, 4)

<tf.Tensor: id=21, shape=(), dtype=int32, numpy=7>

In [37]:
np.add([1,2], [3,4])

array([4, 6])

In [36]:
tf.add([1,2], [3,4])

<tf.Tensor: id=24, shape=(2,), dtype=int32, numpy=array([4, 6])>

numpy와 마찬가지로 broadcasting 지원한다.

In [45]:
np.add([1,2,3,4], 5)

array([6, 7, 8, 9])

In [44]:
tf.add([1,2,3,4], 5)

<tf.Tensor: id=37, shape=(4,), dtype=int32, numpy=array([6, 7, 8, 9])>

tensor는 numpy보다 우아하다.  

numpy에서 모호한 점을 더 직관적으로 수정했다.  

In [38]:
# reduce는 값을 하나로 축약한다.
b = np.add.reduce([1,2,3])

In [39]:
# numpy보다 직관적으로 사용할 수 있다. 
bb = tf.reduce_sum([1,2,3])

In [40]:
b

6

In [41]:
bb

<tf.Tensor: id=31, shape=(), dtype=int32, numpy=6>

행렬곱은 `matmul`로 동일하다.

In [46]:
np.matmul([[1]], [[2,3]])

array([[2, 3]])

In [43]:
tf.matmul([[1]], [[2,3]])

<tf.Tensor: id=34, shape=(1, 2), dtype=int32, numpy=array([[2, 3]])>

값을 즉시 확인할 수 있는 eager tensor 모드.

1. tensorflow 1 : imperative style 추가 모듈로 지원했다.
    - 기본적으로 즉시 값을 볼 수 없었다.
2. pytorch : imperative style
    - 즉시 값을 볼 수 있는 스타일로 큰 인기를 끌었다.
3. tensorflow 2 : eager tensor 지원(imperative style 모듈을 기본으로 변경)
    - pytorch가 인기를 끌자 버전업하면서 개정하였다.

---
- numpy로 불러와서 tensor로 바꿔서 사용하면 이론상 리소스를 소비가 발생한다.(빅데이터일경우)
- (numpy > tensor)변환이 (tensor > numpy)변환보다 조금 더 걸린다. 
- 하지만 numpy는 scikit-learn, pandas, matplotlib등 호환되는 라이브러리가 많은 장점이 있다.  
- 데이터를 불러올 때 tensor로 바로 불러오는 게 좋을지 numpy로 불러오는 게 좋을지는 상황에 따라 다르다.

tensor는 numpy와 호환이 잘 된다.
`__array__`와 `__array_priority__`를 가지고 있으면 numpy와 호환이 된다.  

In [47]:
hasattr(aa, '__array__')

True

In [48]:
hasattr(aa, '__array_priority__')

True

### GPU 지원

numpy는 GPU를 지원하지 않는다.  
tensor는 GPU를 지원하는 것이 아주 큰 특징이다.

scikit-learn은 공식적으로 GPU를 지원할 계획이 없다고 밝혔다.  
neural network에서 자동 미분할 때 이외에는 GPU가 더 효율적인 경우가 없다.  
scikit-learn은 neural network의 비중이 낮고, machine-learning 알고리즘에서는 GPU가 성능향상 효과가 없기 때문에 cpu밖에 안되지만 vectorization로 속도가 빠른 numpy만으로 충분하다.

## Dataset

### from

In [49]:
from tensorflow.keras.datasets import fashion_mnist

In [50]:
# 기본적으로 hold out
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

In [51]:
# 데이터를 tensor로 변환해서 (60000,28,28) shape으로 꺼내준다.
tf.data.Dataset.from_tensors(X_train)

<TensorDataset shapes: (60000, 28, 28), types: tf.uint8>

In [52]:
# 데이터를 tensor로 변환해서 (28, 28) shape으로 하나씩 꺼내준다.
# from_tensor와는 shape이 다르다.
# from_tensor_slices는 generator처럼 사용 가능하다.
tf.data.Dataset.from_tensor_slices(X_train)

<TensorSliceDataset shapes: (28, 28), types: tf.uint8>

### tfds

In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds

In [2]:
len(tfds.load('mnist', as_supervised=True, with_info=True, shuffle_files=True))

2

In [3]:
data, info = tfds.load('mnist', as_supervised=True, with_info=True, shuffle_files=True)

In [4]:
data

{'test': <DatasetV1Adapter shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>,
 'train': <DatasetV1Adapter shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>}

In [5]:
train, test = data['train'], data['test']

In [6]:
train

<DatasetV1Adapter shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>

In [ ]:
# train을 0 ~ 1로 normalize를 해보자. 
# Error
train/255

In [7]:
x = tf.constant([1.8, 2.2], dtype=tf.float32)

In [8]:
# 데이터 타입을 바꾸는 것을 영어로 type casting이라고 한다.
# cast는 데이터 타입을 바꿔준다.
tf.cast(x, tf.int32)

<tf.Tensor: id=610, shape=(2,), dtype=int32, numpy=array([1, 2])>

In [9]:
# dataset에도 map이 있다. 
# map은 항상 왕이다.
hasattr(train, 'map')

True

함수를 만들어서 `map`을 해보자.

In [10]:
def minmax(img, label):
    return tf.cast(img, tf.float32) / 255., label

In [11]:
train.map(minmax)

<DatasetV1Adapter shapes: ((28, 28, 1), ()), types: (tf.float32, tf.int64)>

In [12]:
# AUTOTUNE은 내부적으로 map을 우아하게 처리해준다. (자동 최적화)
train.map(minmax, num_parallel_calls=tf.data.experimental.AUTOTUNE)

<DatasetV1Adapter shapes: ((28, 28, 1), ()), types: (tf.float32, tf.int64)>

GPU를 쓰기 때문에 `cache`, `prefetch`를 지원한다.

In [13]:
# 캐시 기능을 지원한다.
# get_file 함수에서도 캐시를 본 적이 있다.
train.cache()

<DatasetV1Adapter shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>

In [14]:
# 데이터를 GPU메모리로 prefetching시켜서 효율적
train.prefetch(tf.data.experimental.AUTOTUNE)

<DatasetV1Adapter shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>

In [15]:
# 128개씩 데이터를 배치시켜준다.
# 사용자가 지정할 수 있다.
train.batch(128)

<DatasetV1Adapter shapes: ((None, 28, 28, 1), (None,)), types: (tf.uint8, tf.int64)>

In [16]:
# 데이터 6만개를 섞는다.
train.shuffle(60000)

<DatasetV1Adapter shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>

In [17]:
# info에 데이터 개수가 있다.
info.splits['train'].num_examples

60000

In [18]:
# 좀 더 우아한 방법
train.shuffle(info.splits['train'].num_examples)

<DatasetV1Adapter shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>

### 연습

In [19]:
# cache와 prefetch는 안해도 된다.
# 효율을 위해서 사용한다.
train_ = train.map(minmax, num_parallel_calls=tf.data.experimental.AUTOTUNE) # AUTOTUNE은 CPU, GPU 알아서 효율적으로 해준다.
                                                             # num_parallel_calls은 사용할 코어수를 정할 수 있다.  
train_ = train_.shuffle(info.splits['train'].num_examples)
train_ = train_.batch(128)
train_ = train_.cache() # 기존에 한번 썼던 것을 캐시해둔다.
train_ = train_.prefetch(tf.data.experimental.AUTOTUNE)

In [20]:
test_ = test.map(minmax, num_parallel_calls=tf.data.experimental.AUTOTUNE)  
# test_ = test_.shuffle(info.splits['test'].num_examples) # test데이터는 셔플할 의미가 없다.
test_ = test_.batch(128) 
test_ = test_.cache()
test_ = test_.prefetch(tf.data.experimental.AUTOTUNE) 

In [21]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28, 1)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [22]:
model.compile(loss='sparse_categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(0.001), metrics=['acc'])

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.fit(train_, epochs=5, validation_data=test_)

Epoch 1/5
469/469 [==============================] - 14s 31ms/step - loss: 0.3567 - acc: 0.9021 - val_loss: 0.0000e+00 - val_acc: 0.0000e+00
Epoch 2/5
469/469 [==============================] - 2s 5ms/step - loss: 0.1674 - acc: 0.9529 - val_loss: 0.1405 - val_acc: 0.9588
Epoch 3/5
469/469 [==============================] - 3s 5ms/step - loss: 0.1194 - acc: 0.9659 - val_loss: 0.1167 - val_acc: 0.9666
Epoch 4/5
469/469 [==============================] - 3s 5ms/step - loss: 0.0918 - acc: 0.9736 - val_loss: 0.1011 - val_acc: 0.9709
Epoch 5/5
469/469 [==============================] - 2s 5ms/step - loss: 0.0733 - acc: 0.9790 - val_loss: 0.0896 - val_acc: 0.9739


`as_supervised=False`를 하면 어떻게 되는지 확인해보자

In [25]:
data2 = tfds.load('mnist', as_supervised=False, with_info=False, shuffle_files=True)

In [26]:
train2, test2 = data2['train'], data2['test']

In [ ]:
# Error
# supervised=False이기 때문에 map에서 값이 하나씩 전달된다.
# minmax는 인자가 2개가 필요하므로 인자 수가 안 맞아서 에러가 발생한다.
train2_ = train2.map(minmax)

In [28]:
train2_ = train2.batch(128)
test2_ = test2.batch(128)

In [29]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28, 1)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [30]:
model.compile(loss='sparse_categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(0.001), metrics=['acc'])

In [ ]:
# Error
# as_supervised=False는 지도학습에 사용할 수 없다.
model.fit(train2_)

In [32]:
# as_supervised=False는 데이터를 dictionary로 꺼내준다.
for i in train2_.take(1):
    print(i)

{'image': <tf.Tensor: id=10170, shape=(128, 28, 28, 1), dtype=uint8, numpy=
array([[[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]]],


       [[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        

In [38]:
# as_supervised=True는 데이터를 tuple로 꺼내준다. -> 학습 가능
# 데이터 하나를 꺼내보기 위해서 for를 쓰거나 iter를 쓸 수 있다.
next(iter(train_.take(1)))

(<tf.Tensor: id=10224, shape=(128, 28, 28, 1), dtype=float32, numpy=
 array([[[[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],
 
         ...,
 
         [[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]]],
 
 
        [[[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],
 
